#include <fstream>
#include <math.h>
#include <limits.h>
#include <string.h>
#include <time.h>
#include <unistd.h>
#include <stdio.h>
#include <ctype.h>
#include <sys/time.h>
#include <sys/resource.h>
#include <iostream>
#include <sstream>
#include <stdlib.h>

using namespace std;

char sysfile[512];
char outfile[512];
int nroao;
int nroa;
long long int nrofint;

extern void get_sys_size(char* sysfile, int* nroao, int* nroa, long long int* nrofint);
extern void read_sys(char* sysfile, double* coord, double* charges, double* mass,
                     double* Hmat, double* Tmat, double* Smat,  double* Dx, double* Dy,
                     double *Dz, long long int* sortcount, double* intval,
                     unsigned short* intnums);

int main(int argc, char* argv[]){
    if(argc != 3){
	cerr << "Usage: ./readsys sysfile outfile\n";
	exit(1);
    }
    sprintf(sysfile, "%s", argv[1]);                                                                        // writes the name of the sysfile generated by mk_in
    sprintf(outfile, "%s", argv[2]);                                                                        // writes the name of the output file
    get_sys_size(sysfile, &nroao, &nroa, &nrofint);                                                         // reads the #AOs, #atoms, and the #integrals from the sysfile
    ofstream outf;                                                                                          // defines an output filestream
    outf.open(outfile);                                                                                     // opens the output file
    outf << "Read Sysfile: " << sysfile << "\n";                                                            // writes the name of the sysfile,
    outf << "Number of atomic orbitals: " << nroao << "\n";                                                 // the number of AOs,
    outf << "Number of atoms: " << nroa << "\n";                                                            // the number of atoms,
    outf << "Number of integrals: " << nrofint << "\n";                                                     // and the number of integrals
    outf.flush();                                                                                           // flushes the output buffer
    double* coord = new double[3*nroa];                                                                     // coordinates of the atoms
    double* charges = new double[nroa];                                                                     // charges of the atom cores
    double* mass = new double[nroa];                                                                        // masses of the atoms
    double* Hmat = new double[nroao*nroao];                                                                 // Hamiltonian matrix
    double* Tmat = new double[nroao*nroao];                                                                 // Kinetic energy matrix
    double* Smat = new double[nroao*nroao];                                                                 // Overlap matrix
    double* Dx   = new double[nroao*nroao];                                                                 // Dipole moment along x
    double* Dy   = new double[nroao*nroao];                                                                 // Dipole moment along y
    double* Dz   = new double[nroao*nroao];                                                                 // Dipole moment along z
    long long int sortcount[4];
    double* intval = new double[nrofint];
    unsigned short* intnums = new unsigned short[nrofint*4];

    read_sys(sysfile, coord, charges, mass, Hmat, Tmat, Smat, Dx, Dy, Dz, sortcount, intval, intnums);
    outf << "------------------------------------------------------------------\n";
    outf << "Output of coordinates, charges and masses (index, x, y, z, q, m): \n";
    for(int i = 0; i < nroa; i++){
	outf << i << " " << coord[i*3+0] << " " << coord[i*3+1] << " " << coord[i*3+2] << " " << charges[i] << " " << mass[i] << "\n";
	outf.flush();
    }
    outf << "------------------------------------------------------------------------------\n";
    outf << "Two electron integral indices and values (index, intnums[i*4+0...3], intval): \n";
    for(int i = 0; i < nrofint; i++){
	outf << i << " " << intnums[i*4+0] << " " << intnums[i*4+1] << " " << intnums[i*4+2] << " " << intnums[i*4+3] << " " << intval[i] << "\n";
	outf.flush();
    }
}

